import type { PresentationDocument, Slide } from "./presentation-schema";

const starterTimestamp = "2026-01-01T00:00:00.000Z";

export function createStarterDocument(): PresentationDocument {
  const accent = "#6650a4";
  const slides: Slide[] = [
    {
      id: "starter-cover",
      title: "Vibe PPT",
      background: "#f7f5fb",
      transition: "fade",
      notes: "用一句话介绍主题，再说明这份演示将带听众走向哪里。",
      elements: [
        {
          id: "starter-accent",
          type: "shape",
          name: "Accent block",
          x: 70,
          y: 72,
          w: 22,
          h: 576,
          rotation: 0,
          opacity: 1,
          locked: false,
          shape: "rectangle",
          fill: accent,
          stroke: "transparent",
          strokeWidth: 0,
          radius: 11,
        },
        {
          id: "starter-title",
          type: "text",
          name: "Title",
          x: 132,
          y: 190,
          w: 920,
          h: 145,
          rotation: 0,
          opacity: 1,
          locked: false,
          text: "把想法，讲得更好。",
          fontFamily: "var(--font-sans)",
          fontSize: 78,
          fontWeight: 700,
          lineHeight: 1.05,
          letterSpacing: -2.8,
          color: "#211d28",
          align: "left",
          valign: "top",
          animation: { enter: "fade-up", delay: 0, duration: 0.6 },
        },
        {
          id: "starter-subtitle",
          type: "text",
          name: "Subtitle",
          x: 136,
          y: 362,
          w: 760,
          h: 92,
          rotation: 0,
          opacity: 1,
          locked: false,
          text: "在右侧告诉 AI 你的目标，它会创建、改写并整理整份演示。",
          fontFamily: "var(--font-sans)",
          fontSize: 26,
          fontWeight: 430,
          lineHeight: 1.4,
          letterSpacing: 0,
          color: "#6c6575",
          align: "left",
          valign: "top",
        },
        {
          id: "starter-page-number",
          type: "text",
          name: "Page number",
          x: 1095,
          y: 620,
          w: 110,
          h: 32,
          rotation: 0,
          opacity: 1,
          locked: false,
          text: "01",
          fontFamily: "var(--font-mono)",
          fontSize: 18,
          fontWeight: 600,
          lineHeight: 1,
          letterSpacing: 1,
          color: accent,
          align: "right",
          valign: "middle",
        },
      ],
    },
  ];

  return {
    format: "vibe-ppt/1",
    version: 1,
    id: "starter-document",
    title: "未命名演示",
    size: { width: 1280, height: 720 },
    theme: {
      background: "#f7f5fb",
      surface: "#ffffff",
      text: "#211d28",
      muted: "#6c6575",
      accent,
      fontFamily: "var(--font-sans)",
      headingFamily: "var(--font-sans)",
    },
    slides,
    createdAt: starterTimestamp,
    updatedAt: starterTimestamp,
  };
}
